<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="pcch-divyag" name="zf.test.ZFAddSingleGatewayTest" tests="5" failures="3" timestamp="29 Mar 2019 15:36:01 GMT" time="783.896" errors="0">
  <testcase name="Tc02AddSingleGatewayWithMacIDAlreadyExists" time="172.234" classname="zf.test.ZFAddSingleGatewayTest"/>
  <testcase name="Tc01AddSingleGatewayWithAllValidInputs" time="178.464" classname="zf.test.ZFAddSingleGatewayTest">
    <failure type="java.lang.AssertionError" message="Expected value is : SUCCESS      Actual value is : Failed">
      <![CDATA[java.lang.AssertionError: Expected value is : SUCCESS      Actual value is : Failed
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.compareText(ExtentReport.java:156)
at zf.pages.ZFAddSingleGatewayPage.verifyToastermessage(ZFAddSingleGatewayPage.java:247)
at zf.pages.ZFAddSingleGatewayPage.addSingleGatewayWithAllValidInputs(ZFAddSingleGatewayPage.java:76)
at zf.test.ZFAddSingleGatewayTest.Tc01AddSingleGatewayWithAllValidInputs(ZFAddSingleGatewayTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Tc01AddSingleGatewayWithAllValidInputs -->
  <testcase name="Tc03AddSingleGatewayWithCertificateAlreadyExists" time="172.859" classname="zf.test.ZFAddSingleGatewayTest">
    <failure type="java.lang.AssertionError" message="Expected value is : Failed      Actual value is : SUCCESS">
      <![CDATA[java.lang.AssertionError: Expected value is : Failed      Actual value is : SUCCESS
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.compareText(ExtentReport.java:156)
at zf.pages.ZFAddSingleGatewayPage.verifyToastermessage(ZFAddSingleGatewayPage.java:247)
at zf.pages.ZFAddSingleGatewayPage.addSingleGatewayWithCertificateAlreadyExists(ZFAddSingleGatewayPage.java:164)
at zf.test.ZFAddSingleGatewayTest.Tc03AddSingleGatewayWithCertificateAlreadyExists(ZFAddSingleGatewayTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Tc03AddSingleGatewayWithCertificateAlreadyExists -->
  <testcase name="Tc05AddSingleGatewayWithoutMandatoryInputs" time="109.817" classname="zf.test.ZFAddSingleGatewayTest"/>
  <testcase name="Tc04AddSingleGatewayWithMandatoryFields" time="150.522" classname="zf.test.ZFAddSingleGatewayTest">
    <failure type="java.lang.AssertionError" message="Expected value is : SUCCESS      Actual value is : Failed">
      <![CDATA[java.lang.AssertionError: Expected value is : SUCCESS      Actual value is : Failed
at org.testng.Assert.fail(Assert.java:96)
at framework.ExtentReport.compareText(ExtentReport.java:156)
at zf.pages.ZFAddSingleGatewayPage.verifyToastermessage(ZFAddSingleGatewayPage.java:247)
at zf.pages.ZFAddSingleGatewayPage.addSingleGatewayWithMandatoryFields(ZFAddSingleGatewayPage.java:199)
at zf.test.ZFAddSingleGatewayTest.Tc04AddSingleGatewayWithMandatoryFields(ZFAddSingleGatewayTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Tc04AddSingleGatewayWithMandatoryFields -->
</testsuite> <!-- zf.test.ZFAddSingleGatewayTest -->
